# Generated by Django 5.2.16 on 2026-07-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleetsettings_videos_dir'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(help_text='Directory name the frames + classes.txt are written under (source root).', max_length=255)),
                ('every_n_frames', models.PositiveIntegerField(default=30, help_text='Save every Nth frame.')),
                ('max_frames_per_video', models.PositiveIntegerField(blank=True, help_text='Optional cap on frames saved.', null=True)),
                ('image_ext', models.CharField(default='.jpg', max_length=8)),
                ('classes_text', models.TextField(blank=True, help_text='One class per line; written verbatim to classes.txt.')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='queued', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('frames_extracted', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='fleet.dataset')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
