# Generated by Django 5.2.16 on 2026-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_frameextractionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameextractionjob',
            name='only_with_people',
            field=models.BooleanField(default=False, help_text='Discard frames with no person detected by the people-detector model.'),
        ),
        migrations.AddField(
            model_name='frameextractionjob',
            name='similarity_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Perceptual-hash Hamming distance (0-64) at or below which a frame is dropped as a near-duplicate of the previously kept frame; blank disables dedup.', null=True),
        ),
        migrations.AddField(
            model_name='frameextractionjob',
            name='frames_dropped_similar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frameextractionjob',
            name='frames_dropped_no_person',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
