# Generated by Django 5.2.16 on 2026-07-27 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_alter_experiment_detector_min_box_size'),
        ('videos', '0003_frameextractionjob_people_similar'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_threshold', models.FloatField(default=0.5, help_text='Detections below this confidence are dropped.')),
                ('frame_stride', models.PositiveIntegerField(default=1, help_text='Run inference every Nth frame; frames in between reuse the last inferred boxes. Higher = faster, less temporally precise.')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='queued', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('output_filename', models.CharField(blank=True, help_text='File name under <videos_root>/inferred/ holding the annotated video.', max_length=512)),
                ('frames_total', models.PositiveIntegerField(blank=True, null=True)),
                ('frames_processed', models.PositiveIntegerField(blank=True, help_text='Number of frames actually run through the model.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_inference_jobs', to='training.trainedmodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='videos.video')),
            ],
            options={
                'verbose_name': 'Inferred video',
                'verbose_name_plural': 'Inferred videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
