# Generated by Django 5.2.16 on 2026-07-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_trainingsettings_exports_root_and_more'),
        ('videos', '0004_inferencejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='artifact_path',
            field=models.CharField(blank=True, help_text="Path of the exported .onnx/.engine relative to the export output directory. Set when model_source is 'exported'.", max_length=1024),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='chain',
            field=models.JSONField(blank=True, default=list, help_text="Ordered pipeline names for the 'chain' pipeline."),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='detector_checkpoint',
            field=models.CharField(blank=True, help_text='Person-detector checkpoint; required for people_detect_first / batch_people (and any chain including them).', max_length=1024),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='detector_expand_ratio',
            field=models.FloatField(blank=True, help_text="Grow each detected person box by this fraction before cropping. Blank = chachak's default. Match what the model was trained with.", null=True, verbose_name='Person-box expand ratio'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='detector_min_box_size',
            field=models.FloatField(blank=True, help_text="Grow person crops smaller than this many pixels rather than dropping them. Blank = chachak's default. Only used by people_detect_first.", null=True, verbose_name='Person-crop minimum size (px)'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='model_source',
            field=models.CharField(choices=[('trained', 'trained model (.pt checkpoint)'), ('exported', 'exported artifact (ONNX / TensorRT)')], default='trained', help_text='Where the model comes from: the trained-models catalogue, or an exported artifact in the export output directory.', max_length=16),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='overlap',
            field=models.FloatField(blank=True, help_text='Fraction (0–1) by which adjacent tiles overlap. Blank = default.', null=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='pipeline',
            field=models.CharField(choices=[('raw', 'raw — whole frame straight to the model'), ('batch_detect', 'batch_detect — tile, detect per tile, merge'), ('people_detect_first', 'people_detect_first — detect people, crop, detect per crop'), ('batch_people', 'batch_people — tile, detect people, crop, detect per crop'), ('chain', 'chain — run several pipelines and merge')], default='raw', help_text="How each frame is presented to the model: whole ('raw'), tiled, or cropped around detected people.", max_length=32),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='tile_height_pct',
            field=models.FloatField(blank=True, help_text="Tile height as a percent (0–100] of each frame's height. Blank = chachak's default.", null=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='tile_size_px',
            field=models.PositiveIntegerField(blank=True, help_text='Fixed square tile size for batch_detect; overrides the tile width/height percentages. Blank = percentage tiling.', null=True, verbose_name='Tile size (pixels)'),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='tile_width_pct',
            field=models.FloatField(blank=True, help_text="Tile width as a percent (0–100] of each frame's width. Blank = chachak's default.", null=True),
        ),
        migrations.AlterField(
            model_name='inferencejob',
            name='trained_model',
            field=models.ForeignKey(blank=True, help_text="Set when model_source is 'trained'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_inference_jobs', to='training.trainedmodel'),
        ),
    ]
