# Generated by Django 5.2.16 on 2026-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_inferencejob_artifact_path_inferencejob_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='merge_nms_iou',
            field=models.FloatField(blank=True, help_text="Class-aware NMS IoU used to merge predictions across tiles/crops. Blank = chachak's default. Match what the model was trained with.", null=True, verbose_name='merge_nms_iou_threshold'),
        ),
    ]
