# Generated by Django 5.2.16 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_inferencejob_merge_nms_iou'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='bundle_path',
            field=models.CharField(blank=True, help_text="Path of the bundle directory relative to the bundle root. Set when model_source is 'bundle'; the bundle's manifest supplies the model, the detector and the whole pipeline geometry.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='inferencejob',
            name='model_source',
            field=models.CharField(choices=[('trained', 'trained model (.pt checkpoint)'), ('exported', 'exported artifact (ONNX / TensorRT)'), ('bundle', 'infer bundle (self-contained pipeline directory)')], default='trained', help_text='Where the model comes from: the trained-models catalogue, an exported artifact in the export output directory, or a self-contained infer bundle under the bundle root.', max_length=16),
        ),
    ]
