# Generated by Django 5.2.17 on 2026-09-01 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VlmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('backend', models.CharField(choices=[('transformers', 'HF transformers (local GPU)'), ('ollama', 'Ollama (not wired up yet)')], default='transformers', help_text='Where the model runs. Ollama is not wired up yet.', max_length=16)),
                ('family', models.CharField(choices=[('qwen2_vl', 'Qwen2.5-VL'), ('smolvlm', 'SmolVLM / Moondream'), ('internvl_llava', 'InternVL / LLaVA-style')], help_text='Which adapter loads it — picks the weights offered below.', max_length=32)),
                ('weights', models.CharField(help_text="Hugging Face repo id (transformers) or model tag (ollama). huggingface.co is unreachable from this network: the repo's snapshot must already be present in data/hf_cache/hub.", max_length=512)),
                ('variant', models.CharField(blank=True, help_text='e.g. 3B, 7B — display only.', max_length=32)),
                ('prompt', models.TextField(help_text='Sent with every sampled frame. Every response becomes an alert, so a prompt that always answers will produce an alert per frame.')),
                ('max_new_tokens', models.PositiveIntegerField(default=128, help_text='Caps the answer length — and so the per-frame latency.')),
                ('quantization', models.CharField(blank=True, choices=[('', 'none (bf16/fp16)'), ('8bit', '8-bit'), ('4bit', '4-bit')], default='', help_text='transformers backend only; ignored by ollama.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VLM model',
                'verbose_name_plural': 'Models',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VlmVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (defaults to the file name without extension).', max_length=255, unique=True)),
                ('filename', models.CharField(blank=True, help_text='File name under the VLM videos root.', max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Link the video was downloaded from (empty for uploads/imports).', max_length=1024)),
                ('quality', models.CharField(blank=True, help_text='Requested max height for downloads (e.g. 1080), or blank for best.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('downloading', 'downloading'), ('ready', 'ready'), ('error', 'error')], default='ready', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('source_fps', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VLM video',
                'verbose_name_plural': 'Videos',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VlmRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_config_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('model_label_snapshot', models.CharField(blank=True, max_length=255)),
                ('fps', models.FloatField(help_text='Requested sampling rate, in frames per second.')),
                ('frame_stride', models.PositiveIntegerField(blank=True, help_text="Resolved from the video's own fps once the run starts.", null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error'), ('cancel_requested', 'cancel requested'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('frames_total', models.PositiveIntegerField(blank=True, help_text='Estimated number of frames that will be sampled.', null=True)),
                ('frames_processed', models.PositiveIntegerField(default=0)),
                ('alerts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('vlm_model', models.ForeignKey(blank=True, help_text='For admin linking/filtering only — the snapshots below are authoritative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='vlm.vlmmodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='vlm.vlmvideo')),
            ],
            options={
                'verbose_name': 'VLM run',
                'verbose_name_plural': 'VLM runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VlmAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='Monotonic within the run, from 1.')),
                ('frame_index', models.PositiveIntegerField(help_text='Index into the decoded frame stream, not the sampled one.')),
                ('video_timestamp_seconds', models.FloatField(help_text='Where in the video this frame came from.')),
                ('text', models.TextField(help_text='Raw model output — unfiltered.')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vlm.vlmrun')),
            ],
            options={
                'verbose_name': 'VLM alert',
                'verbose_name_plural': 'VLM alerts',
                'ordering': ['run', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='vlm_vlmaler_run_id_b64047_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='vlm_alert_run_seq_unique')],
            },
        ),
    ]
