# Generated by Django 5.2.17 on 2026-09-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_fleetsettings_vlm_videos_dir'),
        ('vlm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlmDatasetRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('model_config_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt_snapshot', models.TextField(blank=True)),
                ('model_label_snapshot', models.CharField(blank=True, max_length=255)),
                ('image_limit', models.PositiveIntegerField(default=0, help_text='Cap on images to run (0 = all). The subset is taken at an even stride so it spans the whole dataset rather than its first N files.')),
                ('grade', models.BooleanField(default=False, help_text="Compare every answer against the image's YOLO label file and report accuracy. Needs the dataset's labels/ folder.")),
                ('negation_aware', models.BooleanField(default=True, help_text='Read a negated mention (“no helmet”) as absent rather than present. Without this, question-shaped prompts score inverted.')),
                ('classes_snapshot', models.JSONField(blank=True, default=list, help_text='The classes.txt this run was scored against, in file order.')),
                ('alias_map', models.JSONField(blank=True, default=dict, help_text="Extra terms per class, {class: [alias, …]}. The class's own name is always matched.")),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Scores from the last grading pass (vlm.services.grading.metrics).')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error'), ('cancel_requested', 'cancel requested'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('images_total', models.PositiveIntegerField(blank=True, help_text='How many images this run will ask about.', null=True)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='For admin linking only — the snapshots below are authoritative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlm_dataset_runs', to='fleet.dataset')),
                ('vlm_model', models.ForeignKey(blank=True, help_text='For admin linking/filtering only — the snapshots below are authoritative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_runs', to='vlm.vlmmodel')),
            ],
            options={
                'verbose_name': 'dataset run',
                'verbose_name_plural': 'Dataset runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VlmDatasetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='Monotonic within the run, from 1.')),
                ('image_filename', models.CharField(max_length=512)),
                ('text', models.TextField(blank=True, help_text='Raw model output — unfiltered.')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, help_text="Why this one image produced no answer, if it didn't.")),
                ('has_label', models.BooleanField(default=False, help_text='A label file exists for this image (possibly empty).')),
                ('gt_classes', models.JSONField(blank=True, default=list)),
                ('predicted_classes', models.JSONField(blank=True, default=list)),
                ('matched', models.BooleanField(blank=True, help_text='Answer named exactly the labeled classes. None when ungraded.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='vlm.vlmdatasetrun')),
            ],
            options={
                'verbose_name': 'dataset result',
                'verbose_name_plural': 'dataset results',
                'ordering': ['run', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='vlm_vlmdata_run_id_6fa488_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='vlm_dataset_result_run_seq_unique')],
            },
        ),
    ]
