# Generated by Django 5.2.17 on 2026-09-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0013_alter_annotationtag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AugPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Short id, used in generated file names (e.g. night_cctv).', max_length=64, unique=True)),
                ('text', models.TextField(help_text='The instruction sent to the editor.')),
                ('negative_prompt', models.TextField(blank=True, help_text="What to steer away from. Blank sends FireRed's default ' '.")),
                ('description', models.CharField(blank=True, max_length=255)),
                ('builtin', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'Prompt library',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AugSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(choices=[('firered', 'FireRed-Image-Edit-1.1'), ('mock', 'Mock — classical filters, no GPU (testing only)')], default='firered', max_length=16)),
                ('transformer', models.CharField(choices=[('q4_k_m', '4-bit q4_k_m — fits a 16 GB GPU'), ('q4_1', '4-bit q4_1'), ('bf16', 'bf16 — full quality, needs ~45 GB of GPU')], default='q4_k_m', help_text="FireRed only. The 4-bit files are what fit this machine's GPU.", max_length=16)),
                ('lightning', models.BooleanField(default=False, help_text="FireRed's official 8-step Lightning LoRA: ~5x faster per image, slightly less faithful. Steps/CFG are forced to 8/1.0.")),
                ('validation_enabled', models.BooleanField(default=True, help_text='Check every variant against its source before copying the labels onto it. Off means every variant is trusted.')),
                ('max_bbox_drift', models.FloatField(default=0.05, help_text='Reject if any box moved more than this fraction of its size.')),
                ('min_box_similarity', models.FloatField(default=0.45, help_text="Reject if any box's structure correlates less than this with the source (0-1; lighting/colour changes do not lower it).")),
                ('max_global_shift', models.FloatField(default=0.02, help_text='Reject if the whole scene shifted more than this fraction of the frame diagonal (camera moved / reframed).')),
                ('name', models.CharField(max_length=255)),
                ('label_source', models.CharField(choices=[('source', 'source labels'), ('annotator', 'annotator output'), ('explicit', 'explicit path')], default='source', max_length=16)),
                ('explicit_labels_path', models.CharField(blank=True, help_text="Required when label source is 'explicit path'.", max_length=1024)),
                ('preview_count', models.PositiveSmallIntegerField(default=3, help_text='How many images each prompt is previewed on.')),
                ('preview_images', models.JSONField(blank=True, default=list, help_text='File names of the preview images (picked automatically).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annotator', models.ForeignKey(blank=True, help_text="Required when label source is 'annotator output'.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.annotator')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.dataset')),
            ],
            options={
                'verbose_name': 'studio session',
                'verbose_name_plural': 'Studio',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AugBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(choices=[('firered', 'FireRed-Image-Edit-1.1'), ('mock', 'Mock — classical filters, no GPU (testing only)')], default='firered', max_length=16)),
                ('transformer', models.CharField(choices=[('q4_k_m', '4-bit q4_k_m — fits a 16 GB GPU'), ('q4_1', '4-bit q4_1'), ('bf16', 'bf16 — full quality, needs ~45 GB of GPU')], default='q4_k_m', help_text="FireRed only. The 4-bit files are what fit this machine's GPU.", max_length=16)),
                ('lightning', models.BooleanField(default=False, help_text="FireRed's official 8-step Lightning LoRA: ~5x faster per image, slightly less faithful. Steps/CFG are forced to 8/1.0.")),
                ('validation_enabled', models.BooleanField(default=True, help_text='Check every variant against its source before copying the labels onto it. Off means every variant is trusted.')),
                ('max_bbox_drift', models.FloatField(default=0.05, help_text='Reject if any box moved more than this fraction of its size.')),
                ('min_box_similarity', models.FloatField(default=0.45, help_text="Reject if any box's structure correlates less than this with the source (0-1; lighting/colour changes do not lower it).")),
                ('max_global_shift', models.FloatField(default=0.02, help_text='Reject if the whole scene shifted more than this fraction of the frame diagonal (camera moved / reframed).')),
                ('source_labels_dir', models.CharField(max_length=1024)),
                ('output_name', models.CharField(help_text='Directory (and Dataset row) name under the source root.', max_length=255)),
                ('prompts_snapshot', models.JSONField(default=list)),
                ('fraction', models.FloatField(default=0.3)),
                ('variants_per_image', models.PositiveSmallIntegerField(default=2)),
                ('class_sampling', models.JSONField(blank=True, default=dict)),
                ('seed', models.IntegerField(default=42)),
                ('include_originals', models.BooleanField(default=True)),
                ('force', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ok', 'Ok'), ('error', 'Error'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('waiting_reason', models.CharField(blank=True, max_length=512)),
                ('images_total', models.PositiveIntegerField(default=0)),
                ('images_selected', models.PositiveIntegerField(default=0)),
                ('variants_planned', models.PositiveIntegerField(default=0)),
                ('variants_attempted', models.PositiveIntegerField(default=0)),
                ('variants_accepted', models.PositiveIntegerField(default=0)),
                ('variants_rejected', models.PositiveIntegerField(default=0)),
                ('variants_errored', models.PositiveIntegerField(default=0)),
                ('variants_cached', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.dataset')),
                ('source_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.dataset')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='genaug.augsession')),
            ],
            options={
                'verbose_name': 'dataset build',
                'verbose_name_plural': 'Dataset builds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AugSessionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64)),
                ('text', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('seed', models.IntegerField(default=42)),
                ('num_inference_steps', models.PositiveSmallIntegerField(default=40)),
                ('true_cfg_scale', models.FloatField(default=4.0)),
                ('editor_config', models.JSONField(default=dict)),
                ('keep', models.BooleanField(default=True, help_text='Include this prompt when building the dataset.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ok', 'Ok'), ('error', 'Error'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='genaug.augprompt')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='genaug.augsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AugPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=512)),
                ('output_relpath', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ok', 'Ok'), ('error', 'Error'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('validation', models.JSONField(blank=True, null=True)),
                ('accepted', models.BooleanField(null=True)),
                ('edit_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='genaug.augsessionprompt')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
