# Generated by Django 5.2.16 on 2026-07-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_fleetsettings_videos_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundingSamRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('images_total', models.PositiveIntegerField(default=0)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('images_labeled', models.PositiveIntegerField(default=0)),
                ('detections_written', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grounding_sam_runs', to='fleet.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
