# Generated by Django 5.2.17 on 2026-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_groundingsamrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetsettings',
            name='vlm_videos_dir',
            field=models.CharField(default='data/vlm_videos', help_text='Directory holding VLM video files (uploaded, imported, or downloaded). Deliberately separate from videos_dir: the VLM section owns its own library, so adding a clip there never disturbs the detection Videos tab.', max_length=512),
        ),
    ]
