# Generated by Django 5.2.16 on 2026-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetsettings',
            name='marketing_bundles_dir',
            field=models.CharField(default='data/marketing/bundles', help_text="Where Marketing Studio looks for infer bundles. Deliberately separate from TrainingSettings.bundles_root: the studio ships its own curated set. Must live on the mount the trainer container sees (anything under data/ is), because a bundle's model reaches /predict_image as an absolute path.", max_length=512),
        ),
        migrations.AddField(
            model_name='fleetsettings',
            name='marketing_videos_dir',
            field=models.CharField(default='data/marketing/videos', help_text="Directory holding Marketing Studio's video files. Deliberately separate from videos_dir: the studio owns its own library, and its own <dir>/inferred output folder, so a render there can never collide with an Inferred video from the Videos tab.", max_length=512),
        ),
    ]
