# Generated by Django 5.2.17 on 2026-09-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_fleetsettings_marketing_dirs'),
        ('training', '0038_alter_experiment_detector_min_box_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetInferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('model_source', models.CharField(choices=[('trained', 'trained model (.pt checkpoint)'), ('exported', 'exported artifact (ONNX / TensorRT)'), ('bundle', 'infer bundle (self-contained pipeline directory)')], default='trained', help_text='Where the model comes from: the trained-models catalogue, an exported artifact in the export output directory, or a self-contained infer bundle under the bundle root.', max_length=16)),
                ('model_label_snapshot', models.CharField(blank=True, max_length=512)),
                ('artifact_path', models.CharField(blank=True, help_text="Path of the exported .onnx/.engine relative to the export output directory. Set when model_source is 'exported'.", max_length=1024)),
                ('bundle_path', models.CharField(blank=True, help_text="Path of the bundle directory relative to the bundle root. Set when model_source is 'bundle'; the bundle's manifest supplies the model, the detector and the whole pipeline geometry.", max_length=1024)),
                ('score_threshold', models.FloatField(default=0.5, help_text='Detections below this confidence are dropped.')),
                ('pipeline', models.CharField(choices=[('raw', 'raw — whole image straight to the model'), ('batch_detect', 'batch_detect — tile, detect per tile, merge'), ('people_detect_first', 'people_detect_first — detect people, crop, detect per crop'), ('batch_people', 'batch_people — tile, detect people, crop, detect per crop'), ('chain', 'chain — run several pipelines and merge')], default='raw', help_text="How each image is presented to the model: whole ('raw'), tiled, or cropped around detected people.", max_length=32)),
                ('detector_checkpoint', models.CharField(blank=True, help_text='Person-detector checkpoint; required for people_detect_first / batch_people (and any chain including them).', max_length=1024)),
                ('detector_expand_ratio', models.FloatField(blank=True, help_text="Grow each detected person box by this fraction before cropping. Blank = chachak's default. Match what the model was trained with.", null=True, verbose_name='Person-box expand ratio')),
                ('detector_min_box_size', models.FloatField(blank=True, help_text="Grow person crops smaller than this many pixels rather than dropping them. Blank = chachak's default. Used by people_detect_first / batch_people.", null=True, verbose_name='Person-crop minimum size (px)')),
                ('tile_size_px', models.PositiveIntegerField(blank=True, help_text='Fixed square tile size for batch_detect; overrides the tile width/height percentages. Blank = percentage tiling.', null=True, verbose_name='Tile size (pixels)')),
                ('tile_width_pct', models.FloatField(blank=True, help_text="Tile width as a percent (0–100] of each image's width. Blank = chachak's default.", null=True)),
                ('tile_height_pct', models.FloatField(blank=True, help_text="Tile height as a percent (0–100] of each image's height. Blank = chachak's default.", null=True)),
                ('overlap', models.FloatField(blank=True, help_text='Fraction (0–1) by which adjacent tiles overlap. Blank = default.', null=True)),
                ('merge_nms_iou', models.FloatField(blank=True, help_text="Class-aware NMS IoU used to merge predictions across tiles/crops. Blank = chachak's default. Match what the model was trained with.", null=True, verbose_name='merge_nms_iou_threshold')),
                ('chain', models.JSONField(blank=True, default=list, help_text="Ordered pipeline names for the 'chain' pipeline.")),
                ('image_limit', models.PositiveIntegerField(default=200, help_text='Cap on images to run (0 = all). The subset is taken at an even stride so it spans the whole dataset rather than its first N files.')),
                ('warmup', models.PositiveIntegerField(default=3, help_text='Untimed calls on the first image before the timed loop starts. Never sensibly zero: the first call for a model loads it (and deserializes a TensorRT plan), which is not a frame time.')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error'), ('cancel_requested', 'cancel requested'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('images_total', models.PositiveIntegerField(blank=True, help_text='How many images this run will go through.', null=True)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('detections_total', models.PositiveIntegerField(default=0)),
                ('timings', models.JSONField(blank=True, default=dict, help_text='What the run measured — see fleet.services.dataset_inference.summarize: per-image latency percentiles for the model itself and for the whole round trip, plus stage shares when the trainer reports them.')),
                ('fps', models.FloatField(blank=True, help_text='Images per second the model itself sustained (1000 / mean model latency), warmup excluded.', null=True)),
                ('p50_ms', models.FloatField(blank=True, help_text='Median model latency per image.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, help_text='For admin linking only — the name snapshot below is authoritative.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_runs', to='fleet.dataset')),
                ('trained_model', models.ForeignKey(blank=True, help_text="Set when model_source is 'trained'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_inference_runs', to='training.trainedmodel')),
            ],
            options={
                'verbose_name': 'dataset inference run',
                'verbose_name_plural': 'Dataset inference runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetInferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='Monotonic within the run, from 1.')),
                ('image_filename', models.CharField(max_length=512)),
                ('boxes', models.JSONField(blank=True, default=list, help_text="The model's detections for this image, as /predict_image returns them.")),
                ('detections', models.PositiveIntegerField(default=0)),
                ('model_ms', models.FloatField(blank=True, help_text='Trainer-side inference time for this image (read, preprocess, forward, postprocess). Null when the trainer reports no timing.', null=True)),
                ('request_ms', models.FloatField(blank=True, help_text='Whole round trip measured by the worker, HTTP included.', null=True)),
                ('stages', models.JSONField(blank=True, default=dict, help_text='Trainer-side per-stage split of model_ms, when it reports one.')),
                ('error', models.TextField(blank=True, help_text="Why this one image produced no detections, if it didn't.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fleet.datasetinferencerun')),
            ],
            options={
                'verbose_name': 'dataset inference result',
                'verbose_name_plural': 'dataset inference results',
                'ordering': ['run', 'seq'],
                'indexes': [models.Index(fields=['run', 'seq'], name='fleet_datas_run_id_ae1ec6_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='fleet_dataset_inference_result_run_seq_unique')],
            },
        ),
    ]
