# Generated by Django 5.2.16 on 2026-09-11 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_datasetinferencerun_datasetinferenceresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('frame', 'frame-wide — asked once per image'), ('region', 'box-wide — asked for every region')], default='frame', max_length=16)),
                ('name', models.CharField(help_text='Control name, e.g. occlusion_level. Box-wide tags show this name to the annotator in the region panel.', max_length=64)),
                ('widget', models.CharField(choices=[('checkbox', 'checkboxes (pick any)'), ('radio', 'radio buttons (pick one)'), ('dropdown', 'dropdown (pick one)'), ('multiselect', 'multi-select dropdown (pick any)'), ('rating', 'star rating'), ('text', 'free text')], default='radio', max_length=16)),
                ('choices', models.JSONField(blank=True, default=list, help_text='The options, for the checkbox/radio/dropdown widgets.')),
                ('max_rating', models.PositiveSmallIntegerField(default=5, help_text='Number of stars, for the rating widget.')),
                ('required', models.BooleanField(default=False, help_text='Label Studio refuses to submit until this one is answered.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='fleet.dataset')),
            ],
            options={
                'verbose_name': 'annotation tag',
                'verbose_name_plural': 'annotation tags',
                'ordering': ['dataset', 'scope', 'order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'name'), name='fleet_annotationtag_dataset_name_unique')],
            },
        ),
    ]
