# Generated by Django 5.2.16 on 2026-09-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_dataset_measure_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.annotator'),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='boxes_measured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='boxes_without_person',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='explicit_labels_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='kind',
            field=models.CharField(choices=[('image', 'image statistics (brightness / contrast)'), ('box', 'box measures (person size / pose)')], default='image', max_length=16),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='label_source',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='labels_dir_snapshot',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='output_dir',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='person_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='datasetmeasurerun',
            name='request_yaml_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
