# Generated by Django 5.2.17 on 2026-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_measure_run_box_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtag',
            name='name',
            field=models.CharField(help_text='Control name, e.g. occlusion_level. Doubles as the heading shown above the control, so name it for the annotator.', max_length=64),
        ),
    ]
