"""Auto-generate a minimal Experiment/TrainingRun for the "Fine-tune…" action.

``TrainedModelAdmin.fine_tune`` (see ``training/admin.py``) is a smaller sibling
of ``ExperimentAdmin.generate_run``: instead of an operator building an
Experiment by hand with inline dataset/model rows, it collects only the handful
of knobs that matter for fine-tuning (a dataset, epochs, batch size, DataLoader
worker count, learning rate, an optional freeze-backbone toggle and
early-stopping patience) and this module assembles the same Experiment /
ExperimentDataset / ExperimentModel /
TrainingRun rows ``generate_run`` would, pre-seeded from the source
:class:`~training.models.TrainedModel`:

* its architecture and checkpoint, passed through as ``init_checkpoint`` — the
  same Friendy warm-start mechanism ``ExperimentModelForm``'s "Your model: …"
  weights option already uses;
* its frozen ``pipeline_metadata``, so the run trains through the same chachak
  pipeline the model was originally trained with — per the pipeline-metadata
  convention (see ``training.services.pipeline_meta``), this never re-asks for
  geometry already on record.

The resulting Experiment is flagged ``is_finetune=True`` with ``finetune_source``
set, so ``jobs.finalize_success`` auto-promotes its result (no manual "Promote"
click, unlike an ordinary experiment) and ``training.admin.FineTuningRunAdmin``
lists it under its own "Fine-tuning runs" tab instead of the main "Training
runs" one.
"""

from __future__ import annotations

from dataclasses import dataclass

import django_rq

from training import model_specs
from training.models import (
    Experiment,
    ExperimentDataset,
    ExperimentModel,
    TrainedModel,
    TrainingRun,
)
from training.services import config_gen, pipeline_meta


@dataclass
class FineTuneRequest:
    """Parsed, validated form input for :func:`create_run`."""

    train_dataset: object
    label_source: str = ExperimentDataset.SOURCE
    annotator: object | None = None
    explicit_labels_path: str = ""
    val_dataset: object | None = None
    val_label_source: str = ExperimentDataset.SOURCE
    val_annotator: object | None = None
    val_explicit_labels_path: str = ""
    name: str = ""
    epochs: int = 20
    batch_size: int = 4
    num_workers: int | None = None
    lr: float = 2e-5
    freeze_backbone: bool = False
    early_stopping_patience: int | None = None


def _unique_name(base: str) -> str:
    name = base
    n = 2
    while Experiment.objects.filter(name=name).exists():
        name = f"{base}-{n}"
        n += 1
    return name


def _field_default(field_name: str):
    return Experiment._meta.get_field(field_name).get_default()


def create_run(source: TrainedModel, req: FineTuneRequest) -> TrainingRun:
    """Build the Experiment/dataset/model rows for a fine-tune and enqueue it.

    Raises ``ValueError`` for the same reasons ``config_gen.write_config``
    would (missing checkpoint, unreadable dataset, …) — the caller (the admin
    action) surfaces those as a form error instead of a 500.
    """
    if not source.checkpoint_path:
        raise ValueError(f"{source.name!r} has no checkpoint to fine-tune from.")

    pmeta = pipeline_meta.for_trained_model(source)
    base_name = (req.name or f"{source.name}-ft").strip()
    experiment = Experiment.objects.create(
        name=_unique_name(base_name),
        description=f"Auto-generated by 'Fine-tune model…' on {source.name!r}.",
        epochs=req.epochs,
        batch_size=req.batch_size,
        num_workers=(
            req.num_workers if req.num_workers is not None else _field_default("num_workers")
        ),
        lr=req.lr,
        early_stopping_patience=req.early_stopping_patience,
        # Pipeline geometry: prefilled from the source model's frozen metadata,
        # never re-asked (see training.services.pipeline_meta). A blank/"raw"
        # pipeline_meta.pipeline means plain full-frame training, i.e. Experiment's
        # own blank default.
        pipeline=("" if pmeta["pipeline"] == pipeline_meta.RAW else pmeta["pipeline"]),
        detector_checkpoint=pmeta["detector_checkpoint"],
        detector_expand_ratio=(
            pmeta["detector_expand_ratio"] if pmeta["detector_expand_ratio"] is not None
            else _field_default("detector_expand_ratio")
        ),
        detector_min_box_size=(
            pmeta["detector_min_box_size"] if pmeta["detector_min_box_size"] is not None
            else _field_default("detector_min_box_size")
        ),
        tile_size_px=pmeta["tile_size_px"],
        tile_width_pct=pmeta["tile_width_pct"],
        tile_height_pct=pmeta["tile_height_pct"],
        overlap=pmeta["overlap"],
        merge_nms_iou=pmeta["merge_nms_iou"],
        chain=pmeta["chain"],
        eval_score_threshold=(
            pmeta["score_threshold"] if pmeta["score_threshold"] is not None
            else _field_default("eval_score_threshold")
        ),
        is_finetune=True,
        finetune_source=source,
    )

    ExperimentDataset.objects.create(
        experiment=experiment, dataset=req.train_dataset, role=ExperimentDataset.TRAIN,
        label_source=req.label_source, annotator=req.annotator,
        explicit_labels_path=req.explicit_labels_path,
    )
    if req.val_dataset is not None:
        ExperimentDataset.objects.create(
            experiment=experiment, dataset=req.val_dataset, role=ExperimentDataset.VAL,
            label_source=req.val_label_source, annotator=req.val_annotator,
            explicit_labels_path=req.val_explicit_labels_path,
        )

    params = {model_specs.INIT_CHECKPOINT_KEY: source.checkpoint_path}
    params.update(model_specs.freeze_params(source.arch, req.freeze_backbone))
    ExperimentModel.objects.create(
        experiment=experiment, arch=source.arch, num_classes=source.num_classes, params=params,
    )

    run = TrainingRun.objects.create(experiment=experiment)
    try:
        config_gen.write_config(experiment, run)
    except (ValueError, FileNotFoundError, RuntimeError):
        run.delete()
        experiment.delete()
        raise

    from training import jobs  # local: avoid a jobs <-> services import cycle

    django_rq.get_queue("default").enqueue(jobs.run_training, run.pk, job_timeout=jobs.JOB_TIMEOUT)
    run.status = TrainingRun.QUEUED
    run.save(update_fields=["status"])
    return run
