# Generated by Django 5.2.16 on 2026-09-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sections', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionassignment',
            name='one_section_per_object',
        ),
        migrations.AddConstraint(
            model_name='sectionassignment',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'section'), name='one_membership_per_object_per_section'),
        ),
    ]
