# Generated by Django 5.2.16 on 2026-07-22 09:46

import cameras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name.', max_length=255, unique=True)),
                ('rtsp_url', models.CharField(help_text='Full stream URL, e.g. rtsp://user:pass@10.10.10.24:554/Streaming/Channels/101', max_length=1024, validators=[cameras.models.validate_rtsp_url])),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('online', 'online'), ('offline', 'offline')], default='unknown', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
