# Generated by Django 5.2.16 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('training', '0025_trainingsettings_exports_root_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Run this model continuously over the camera's live frames. The raw preview keeps working either way.")),
                ('target_fps', models.FloatField(default=2.0, help_text='How often the detection boxes refresh, in times per second. The annotated video itself stays as smooth as the live preview — only the boxes are limited by this. Caps GPU load; an upper bound, not a guarantee. Above ~6-7 it has no effect, since the camera preview supplies no new frames faster than that.')),
                ('model_source', models.CharField(choices=[('trained', 'trained model (.pt checkpoint)'), ('exported', 'exported artifact (ONNX / TensorRT)')], default='trained', help_text='Where the model comes from: the trained-models catalogue, or an exported artifact in the export output directory.', max_length=16)),
                ('artifact_path', models.CharField(blank=True, help_text="Path of the exported .onnx/.engine relative to the export output directory. Set when model_source is 'exported'.", max_length=1024)),
                ('score_threshold', models.FloatField(default=0.5, help_text='Detections below this confidence are dropped.')),
                ('pipeline', models.CharField(choices=[('raw', 'raw — whole frame straight to the model'), ('batch_detect', 'batch_detect — tile, detect per tile, merge'), ('people_detect_first', 'people_detect_first — detect people, crop, detect per crop'), ('batch_people', 'batch_people — tile, detect people, crop, detect per crop'), ('chain', 'chain — run several pipelines and merge')], default='raw', help_text="How each frame is presented to the model: whole ('raw'), tiled, or cropped around detected people.", max_length=32)),
                ('detector_checkpoint', models.CharField(blank=True, help_text='Person-detector checkpoint; required for people_detect_first / batch_people (and any chain including them).', max_length=1024)),
                ('detector_expand_ratio', models.FloatField(blank=True, help_text="Grow each detected person box by this fraction before cropping. Blank = chachak's default. Match what the model was trained with.", null=True, verbose_name='Person-box expand ratio')),
                ('detector_min_box_size', models.FloatField(blank=True, help_text="Grow person crops smaller than this many pixels rather than dropping them. Blank = chachak's default. Only used by people_detect_first.", null=True, verbose_name='Person-crop minimum size (px)')),
                ('tile_size_px', models.PositiveIntegerField(blank=True, help_text='Fixed square tile size for batch_detect; overrides the tile width/height percentages. Blank = percentage tiling.', null=True, verbose_name='Tile size (pixels)')),
                ('tile_width_pct', models.FloatField(blank=True, help_text="Tile width as a percent (0–100] of each frame's width. Blank = chachak's default.", null=True)),
                ('tile_height_pct', models.FloatField(blank=True, help_text="Tile height as a percent (0–100] of each frame's height. Blank = chachak's default.", null=True)),
                ('overlap', models.FloatField(blank=True, help_text='Fraction (0–1) by which adjacent tiles overlap. Blank = default.', null=True)),
                ('chain', models.JSONField(blank=True, default=list, help_text="Ordered pipeline names for the 'chain' pipeline.")),
                ('status', models.CharField(choices=[('idle', 'idle'), ('running', 'running'), ('error', 'error')], default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_inference_at', models.DateTimeField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(blank=True, help_text="Round-trip of the most recent /predict_image call, including the frame write and any wait for the trainer's GPU lock.", null=True)),
                ('last_box_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(help_text='The camera whose live frames this model runs on.', on_delete=django.db.models.deletion.CASCADE, related_name='inference', to='cameras.camera')),
                ('trained_model', models.ForeignKey(blank=True, help_text="Set when model_source is 'trained'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_inferences', to='training.trainedmodel')),
            ],
            options={
                'verbose_name': 'Live inference',
                'verbose_name_plural': 'Live inference',
            },
        ),
    ]
