# Generated by Django 5.2.16 on 2026-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camerainference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerainference',
            name='detector_checkpoint',
            field=models.CharField(blank=True, default='models/people/best_ckpt.engine', help_text='Person-detector checkpoint; required for people_detect_first / batch_people (and any chain including them).', max_length=1024),
        ),
    ]
