# Generated by Django 5.2.16 on 2026-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camerainference_bundle_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerainference',
            name='detector_min_box_size',
            field=models.FloatField(blank=True, help_text="Grow person crops smaller than this many pixels rather than dropping them. Blank = chachak's default. Used by people_detect_first / batch_people.", null=True, verbose_name='Person-crop minimum size (px)'),
        ),
    ]
