# Generated by Django 5.2.16 on 2026-09-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this look is called in the preset dropdown.', max_length=120, unique=True)),
                ('style', models.JSONField(default=dict, help_text='The style dict (see videos.services.render_style).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Render preset',
                'verbose_name_plural': 'Render presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (defaults to the file name without extension).', max_length=255, unique=True)),
                ('filename', models.CharField(blank=True, help_text="File name under the studio's video root. Filled in by the download job.", max_length=512)),
                ('source_url', models.URLField(blank=True, help_text='Link the video was downloaded from (empty for imported files).', max_length=1024)),
                ('quality', models.CharField(blank=True, help_text='Requested max height for downloads (e.g. 1080), or blank for best.', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('downloading', 'downloading'), ('ready', 'ready'), ('error', 'error')], default='ready', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_path', models.CharField(help_text="Path of the bundle directory relative to the studio's bundle root. The bundle's manifest supplies the model, the detector and the whole pipeline geometry.", max_length=1024)),
                ('score_threshold', models.FloatField(default=0.5, help_text='Detections below this confidence are dropped.')),
                ('frame_stride', models.PositiveIntegerField(default=1, help_text='Run inference every Nth frame; frames in between reuse the last inferred boxes. Higher = faster, less temporally precise.')),
                ('render_style', models.JSONField(blank=True, default=dict, help_text='Look of the burned-in overlay (see videos.services.render_style).')),
                ('pipeline', models.CharField(choices=[('raw', 'raw — whole frame straight to the model'), ('batch_detect', 'batch_detect — tile, detect per tile, merge'), ('people_detect_first', 'people_detect_first — detect people, crop, detect per crop'), ('batch_people', 'batch_people — tile, detect people, crop, detect per crop'), ('chain', 'chain — run several pipelines and merge')], default='raw', help_text="How each frame is presented to the model: whole ('raw'), tiled, or cropped around detected people.", max_length=32)),
                ('detector_checkpoint', models.CharField(blank=True, max_length=1024)),
                ('detector_expand_ratio', models.FloatField(blank=True, null=True, verbose_name='Person-box expand ratio')),
                ('detector_min_box_size', models.FloatField(blank=True, null=True, verbose_name='Person-crop minimum size (px)')),
                ('tile_size_px', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tile size (pixels)')),
                ('tile_width_pct', models.FloatField(blank=True, null=True)),
                ('tile_height_pct', models.FloatField(blank=True, null=True)),
                ('overlap', models.FloatField(blank=True, null=True)),
                ('merge_nms_iou', models.FloatField(blank=True, null=True, verbose_name='merge_nms_iou_threshold')),
                ('chain', models.JSONField(blank=True, default=list, help_text="Ordered pipeline names for the 'chain' pipeline.")),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='queued', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('output_filename', models.CharField(blank=True, help_text='File name under <marketing_videos_dir>/inferred/ holding the render.', max_length=512)),
                ('frames_total', models.PositiveIntegerField(blank=True, null=True)),
                ('frames_processed', models.PositiveIntegerField(blank=True, help_text='Number of frames actually run through the model.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='marketing_studio.video')),
            ],
            options={
                'verbose_name': 'Inferred video',
                'verbose_name_plural': 'Inferred videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
