# Generated by Django 5.2.16 on 2026-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_experiment_tile_size_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='combined_models',
            field=models.ManyToManyField(blank=True, related_name='+', to='training.trainedmodel'),
        ),
    ]
