# Generated by Django 5.2.16 on 2026-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_alter_experiment_detector_min_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsettings',
            name='exports_root',
            field=models.CharField(default='data/training/runs/exports', help_text='Where exported inference artifacts (.onnx / .engine) are written. Prefilled as the output directory by the ONNX/TensorRT export actions, and scanned recursively to offer exported models for video inference. Point this at an existing directory (e.g. data/training/runs) to pick up artifacts exported before this setting existed.', max_length=512),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='detector_checkpoint',
            field=models.CharField(blank=True, default='models/people/best_ckpt.engine', help_text='Person-detector checkpoint (.pt, .onnx, or .engine); required for people_detect_first / batch_people (and any chain that includes them). Runs at train, val, and test: it selects the person crops the model is trained and evaluated on. Objects outside every detected person crop are not seen during training. TensorRT person engines automatically resize oversized frames while preserving aspect ratio; the default engine has a 1280-pixel maximum side.', max_length=1024),
        ),
    ]
