# Generated by Django 5.2.16 on 2026-07-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_trainedmodel_pipeline_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('onnx', 'onnx'), ('trt', 'trt')], max_length=8)),
                ('checkpoint_label', models.CharField(max_length=16)),
                ('checkpoint_path', models.CharField(max_length=1024)),
                ('output_path', models.CharField(max_length=1024)),
                ('precision', models.CharField(blank=True, max_length=8)),
                ('input_hw', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('ok', 'ok'), ('error', 'error')], default='queued', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('bundle_dir', models.CharField(blank=True, max_length=1024)),
                ('bundle_error', models.TextField(blank=True)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_runs', to='training.trainedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
