# Generated by Django 5.2.16 on 2026-07-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_exportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsettings',
            name='bundles_root',
            field=models.CharField(default='data/bundles', help_text="Where infer bundles live — the self-contained directories chachak's bundle export writes (pipeline.json + models/ + a vendored runtime). Scanned recursively to offer bundles for video and camera inference, so a bundle copied in from another machine shows up in those dropdowns.", max_length=512),
        ),
    ]
