# Generated by Django 5.2.17 on 2026-08-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_alter_experiment_detector_min_box_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Short identifier, also the directory bundles from this node are filed under inside the bundle root.', max_length=64, unique=True)),
                ('base_url', models.CharField(help_text="Where the node's service listens, e.g. http://10.10.155.40:8300", max_length=512)),
                ('token', models.CharField(blank=True, help_text="Must equal the BUILDNODE_TOKEN the node was started with — the node is authoritative, this is a copy. Use the 'Generate a token' action to mint one when setting a node up, then pass the same value to the node's environment.", max_length=128)),
                ('status', models.CharField(choices=[('active', 'active'), ('retired', 'retired')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('gpu_name', models.CharField(blank=True, max_length=128)),
                ('compute_capability', models.CharField(blank=True, max_length=16)),
                ('tensorrt_version', models.CharField(blank=True, max_length=32)),
                ('driver_version', models.CharField(blank=True, max_length=32)),
                ('last_health', models.JSONField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('ok', 'ok'), ('error', 'error'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the node answered a ping successfully.', null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time a ping was attempted, successful or not.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exportrun',
            name='remote_build_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='node',
            field=models.ForeignKey(blank=True, help_text='Blank = built on the local trainer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_runs', to='training.buildnode'),
        ),
    ]
