# Generated by Django 5.2.17 on 2026-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0031_buildnode_exportrun_remote_build_id_exportrun_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='kind',
            field=models.CharField(choices=[('onnx', 'onnx'), ('trt', 'trt'), ('pt', 'pt')], max_length=8),
        ),
    ]
