# Generated by Django 5.2.17 on 2026-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0032_alter_exportrun_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='gpu_infer',
            field=models.BooleanField(default=False),
        ),
    ]
