# Generated by Django 5.2.16 on 2026-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_exportrun_gpu_infer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='arch',
            field=models.CharField(choices=[('retinanet', 'retinanet'), ('yolox', 'yolox'), ('rtdetr', 'rtdetr'), ('rfdetr', 'rfdetr'), ('fasterrcnn', 'fasterrcnn'), ('ecdet', 'ecdet')], default='retinanet', max_length=32),
        ),
    ]
