# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0035_finetuningrun_experiment_finetune_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='min_batch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='opt_batch',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='max_batch',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
