# Generated by Django 5.2.17 on 2026-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0036_exportrun_batch_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentmodel',
            name='arch',
            field=models.CharField(choices=[('retinanet', 'retinanet'), ('yolox', 'yolox'), ('rtdetr', 'rtdetr'), ('rfdetr', 'rfdetr'), ('fasterrcnn', 'fasterrcnn'), ('ecdet', 'ecdet'), ('dfine', 'dfine')], default='retinanet', max_length=32),
        ),
    ]
