# Generated by Django 5.2.17 on 2026-09-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_evalrun_class_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalrun',
            name='test_group',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
